// <auto-generated />
using System;
using Diplomados_VillaVocado.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diplomados_VillaVocado.Migrations
{
    [DbContext(typeof(VillaAvocadoDbContext))]
    [Migration("20251101205440_DataSeedInitial")]
    partial class DataSeedInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diplomados_VillaVocado.Models.CargaDiplomado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiplomadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiplomadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CargaDiplomados", (string)null);
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.CargaMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiplomadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiplomadoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("CargaMaterias", (string)null);
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Diplomado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Diplomados", (string)null);
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materias", (string)null);
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.CargaDiplomado", b =>
                {
                    b.HasOne("Diplomados_VillaVocado.Models.Diplomado", "Diplomado")
                        .WithMany("Diplomados")
                        .HasForeignKey("DiplomadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diplomados_VillaVocado.Models.Usuario", "Usuario")
                        .WithMany("Diplomados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diplomado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.CargaMateria", b =>
                {
                    b.HasOne("Diplomados_VillaVocado.Models.Diplomado", "Diplomado")
                        .WithMany("Materias")
                        .HasForeignKey("DiplomadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diplomados_VillaVocado.Models.Materia", "Materia")
                        .WithMany("Materias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diplomado");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Diplomado", b =>
                {
                    b.Navigation("Diplomados");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Materia", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Usuario", b =>
                {
                    b.Navigation("Diplomados");
                });
#pragma warning restore 612, 618
        }
    }
}
