// <auto-generated />
using System;
using Diplomados_VillaVocado.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diplomados_VillaVocado.Migrations
{
    [DbContext(typeof(VillaAvocadoDbContext))]
    [Migration("20251101225048_Initial-And-DataSeed")]
    partial class InitialAndDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diplomados_VillaVocado.Models.CargaDiplomado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiplomadoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiplomadoId");

                    b.HasIndex("UsuarioId", "DiplomadoId")
                        .IsUnique();

                    b.ToTable("CargaDiplomados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DiplomadoId = 1,
                            Estado = 2,
                            FechaInscripcion = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserCreateId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DiplomadoId = 2,
                            Estado = 1,
                            FechaInscripcion = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserCreateId = 1,
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Diplomado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Diplomados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Aprende .NET y React",
                            FechaFin = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Desarrollo Web Full Stack",
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Metodologías ágiles para gestión de proyectos",
                            FechaFin = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gestión de Proyectos Ágiles",
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Fundamentos y prácticas de ciberseguridad empresarial",
                            FechaFin = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Seguridad Informática",
                            UserCreateId = 1
                        });
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiplomadoId")
                        .HasColumnType("int");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiplomadoId", "Orden")
                        .IsUnique();

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Introducción al desarrollo web con HTML y CSS",
                            DiplomadoId = 1,
                            DuracionHoras = 40,
                            Nombre = "Fundamentos de HTML y CSS",
                            Orden = 1,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Programación con JavaScript moderno y asíncrona",
                            DiplomadoId = 1,
                            DuracionHoras = 60,
                            Nombre = "JavaScript Moderno",
                            Orden = 2,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Desarrollo con React",
                            DiplomadoId = 1,
                            DuracionHoras = 50,
                            Nombre = "React Avanzado",
                            Orden = 3,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Desarrollo de APIs RESTful con .NET",
                            DiplomadoId = 1,
                            DuracionHoras = 50,
                            Nombre = "ASP.NET Core Web API",
                            Orden = 4,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Framework Scrum: roles, eventos y artefactos",
                            DiplomadoId = 2,
                            DuracionHoras = 30,
                            Nombre = "Introducción a Scrum",
                            Orden = 1,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Optimización de flujos de trabajo con Kanban",
                            DiplomadoId = 2,
                            DuracionHoras = 25,
                            Nombre = "Kanban y Lean",
                            Orden = 2,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Comunicación efectiva con interesados del proyecto",
                            DiplomadoId = 2,
                            DuracionHoras = 20,
                            Nombre = "Gestión de Stakeholders",
                            Orden = 3,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Medición de rendimiento en proyectos ágiles",
                            DiplomadoId = 2,
                            DuracionHoras = 20,
                            Nombre = "Métricas y KPIs Ágiles",
                            Orden = 4,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Conceptos básicos de seguridad informática",
                            DiplomadoId = 3,
                            DuracionHoras = 35,
                            Nombre = "Fundamentos de Ciberseguridad",
                            Orden = 1,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Técnicas de pruebas de penetración éticas",
                            DiplomadoId = 3,
                            DuracionHoras = 45,
                            Nombre = "Ethical Hacking",
                            Orden = 2,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "OWASP Top 10 y mejores prácticas",
                            DiplomadoId = 3,
                            DuracionHoras = 40,
                            Nombre = "Seguridad en Aplicaciones Web",
                            Orden = 3,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Identificación y mitigación de riesgos de seguridad",
                            DiplomadoId = 3,
                            DuracionHoras = 30,
                            Nombre = "Gestión de Riesgos",
                            Orden = 4,
                            UserCreateId = 1
                        });
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int?>("UserCreateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Correo = "admin@villaavocado.com",
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Administrador",
                            Password = "QWRtaW4xMjMh",
                            Rol = 2,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Correo = "juan.perez@villaavocado.com",
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan Perez G",
                            Password = "VXNlcjEyMyE=",
                            Rol = 1,
                            UserCreateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Correo = "maria.lopez@villaavocado.com",
                            CreatedAt = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María Lopez",
                            Password = "VXNlcjEyMyE=",
                            Rol = 1,
                            UserCreateId = 1
                        });
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.CargaDiplomado", b =>
                {
                    b.HasOne("Diplomados_VillaVocado.Models.Diplomado", "Diplomado")
                        .WithMany("Diplomados")
                        .HasForeignKey("DiplomadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diplomados_VillaVocado.Models.Usuario", "Usuario")
                        .WithMany("Diplomados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diplomado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Materia", b =>
                {
                    b.HasOne("Diplomados_VillaVocado.Models.Diplomado", "Diplomado")
                        .WithMany("Materias")
                        .HasForeignKey("DiplomadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diplomado");
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Diplomado", b =>
                {
                    b.Navigation("Diplomados");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Diplomados_VillaVocado.Models.Usuario", b =>
                {
                    b.Navigation("Diplomados");
                });
#pragma warning restore 612, 618
        }
    }
}
